spring:
  application:
    name: enggo-backend

  cloud:
    aws:
      region:
        static: ap-northeast-1

  config:
    import: "optional:aws-parameterstore:/config/enggo-backend/"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  signer-key: ${JWT_SIGNER_KEY} # Lấy từ Parameter Store (/config/enggo-backend/JWT_SIGNER_KEY)
  valid-duration: 3600
  refreshable-duration: 36000

aws:
  s3:
    region: ${AWS_REGION}
    bucket-name: ${AWS_S3_BUCKET}
    access-key: ${AWS_S3_ACCESS_KEY} # Lấy từ Parameter Store (/config/enggo-backend/AWS_S3_ACCESS_KEY)
    secret-key: ${AWS_S3_SECRET_KEY} # Lấy từ Parameter Store (/config/enggo-backend/AWS_S3_SECRET_KEY)
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}

app:
  upload:
    max-size: 5242880
    allowed-types:
      - image/jpeg
      - image/png

game:
  levels:
    - { level: 1,  reqExp: 0 }
    - { level: 2,  reqExp: 100 }
    - { level: 3,  reqExp: 250 }
    - { level: 4,  reqExp: 450 }
    - { level: 5,  reqExp: 700 }
    - { level: 6,  reqExp: 1000 }
    - { level: 7,  reqExp: 1350 }
    - { level: 8,  reqExp: 1750 }
    - { level: 9,  reqExp: 2200 }
    - { level: 10, reqExp: 2700 }
    - { level: 11, reqExp: 3300 }
    - { level: 12, reqExp: 4000 }
    - { level: 13, reqExp: 4800 }
    - { level: 14, reqExp: 5700 }
    - { level: 15, reqExp: 6700 }
    - { level: 16, reqExp: 7900 }
    - { level: 17, reqExp: 9300 }
    - { level: 18, reqExp: 10900 }
    - { level: 19, reqExp: 12700 }
    - { level: 20, reqExp: 14700 }
    - { level: 21, reqExp: 17000 }
    - { level: 22, reqExp: 19600 }
    - { level: 23, reqExp: 22500 }
    - { level: 24, reqExp: 25700 }
    - { level: 25, reqExp: 29300 }
    - { level: 26, reqExp: 33300 }
    - { level: 27, reqExp: 37800 }
    - { level: 28, reqExp: 42800 }
    - { level: 29, reqExp: 48400 }
    - { level: 30, reqExp: 55000 }